version: '3.7'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1434:1433
    environment:
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - sqlvolume:/var/opt/mssql
    # restart: always

    networks:
      - sqlserver

volumes:
  sqlvolume:


networks:
  sqlserver:


